### PR TITLE
svg: fix "push after EOF" error

### LINKED ISSUE #52: ERR_STREAM_PUSH_AFTER_EOF in probe-image-size/lib/parse_stream/svg.js:163:20
Test case (test.js):
``` js
let probe = require("probe-image-size");
let Promise = require("bluebird");
let axios = require("axios");
let server = require("express")();

server.post("/probe", async function(req, res)
{
	await new Promise(resolve => setImmediate(resolve));
	await probe(req);
	res.end();
});

let request = axios.create({ baseURL: "http://127.0.0.1:8888", validateStatus: null, maxRedirects: 0 });

let svg = `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100pt" height="100pt" viewBox="0 0 100 100" version="1.1">`;
for(let i = 0; i < 100000; i++) svg += " ";

async function main()
{
	await new Promise(resolve => server.listen(8888, resolve));
	while(true) await request.post("/probe", svg).catch(() => {});
}

main();
```

Install and run (it may take some time):
```
npm install probe-image-size bluebird axios express
node test.js
```

Possible output:
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
    at readableAddChunk (internal/streams/readable.js:272:30)
    at Transform.Readable.push (internal/streams/readable.js:223:10)
    at Transform.push (internal/streams/transform.js:166:32)
    at Transform.transform [as _transform] (.../node_modules/probe-image-size/lib/parse_stream/svg.js:163:20)
    at Transform._read (internal/streams/transform.js:205:10)
    at Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Transform.Writable.write (internal/streams/writable.js:303:10)
    at PassThrough.ondata (internal/streams/readable.js:719:22)
    at PassThrough.emit (events.js:327:22)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at PassThrough.Readable.push (internal/streams/readable.js:223:10)
    at PassThrough.Transform.push (internal/streams/transform.js:166:32)
    at PassThrough.afterTransform (internal/streams/transform.js:101:10)
    at PassThrough._transform (internal/streams/passthrough.js:46:3)
Emitted 'error' event on Transform instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_STREAM_PUSH_AFTER_EOF'
}
```

### PR DESCRIPTION
**Pull request by misos1**
Fixes #52.

Also adds test case which fails without this patch:
```
  1) probeStream
       should not fail when processing svg in multiple chunks:
     Uncaught Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
  2) probeStream
       should not fail when processing svg in multiple chunks:
     Error: done() called multiple times in test <probeStream should not fail when processing svg in multiple chunks> of file probe-image-size/test/test_stream.js
```

### CODE REVIEW

File: lib/parse_stream/svg.js [hunk 1]
```diff
@@ -161,6 +161,7 @@ module.exports = function () {
 
           if (result) {
             parser.push(result);
+            state = STATE_IGNORE;
```
Comment (puzrin) [inline lib/parse_stream/svg.js:164]: I'd suggest move this one line up, to guarantee no races in previous push internals.

Comment (misos1) [reply lib/parse_stream/svg.js:164]: Ok, but I am not sure what you mean, `push` does not call `transform` from itself again. According to documentation it just pushes its argument into stream's internal queue.

Comment (misos1) [reply lib/parse_stream/svg.js:163]: Could you elaborate?

Comment (puzrin) [reply lib/parse_stream/svg.js:163]: If simplify everything, push() calls connected stream, which can do something causing push of next svg chunk. Probability if this case is zero.

Comment (misos1) [reply lib/parse_stream/svg.js:163]: I did a little test. You are right that `push` on the first stream can lead to direct call (not from event loop) of `transform` of second stream into which is first stream piped. I misread documentation, it says that `push` will push data into the internal queue only when data is Buffer, Uint8Array or string (seemingly not when stream is not operating in object mode). But still your `parser` stream would need to be piped into itself to cause possible problems with `state`. And even then or in other circumstances `transform` function will not be called again until it calls `next` callback:

"transform._transform() is never called in parallel; streams implement a queue mechanism, and to receive the next chunk, callback must be called, either synchronously or asynchronously."
